Savingfeature
kenwongz/SimpCity pull request #47
Opened 2022-01-17 07:33 UTC by Harish110

Pull request build highway

2022-01-18 14:15 UTC, CaeNGnp requested changes
- Please revert "House" related commits, see #40 
- Please merge the latest `main` refs to avoid merge conflicts

2022-01-18 14:15 UTC, CaeNGnp commented on SimpCityTests/GameTests.cs
> +{
Please run the formatter again after merging the `main` branch as cecce1c211e5fec5e19935c3a0d31b5d80928e6f updates the format spec.

2022-01-18 14:15 UTC, CaeNGnp commented on SimpCityTests/GameTests.cs
> +        }
Good attempt for making the test script, but this virtually tests nothing with no assertion whatsoever

2022-01-19 06:51 UTC, JSQJ approved these changes
Testing no issues

2022-01-19 08:46 UTC, kenwongz requested changes
@Harish110 please fix the conflict. Please do it by 21/01/22

2022-01-19 12:48 UTC, kenwongz commented
@Harish110 pls take a look at the code again to satisfy the requirement.
![image](https://user-images.githubusercontent.com/42329568/150133805-b1f6e6d0-cd43-4397-8004-ebfd2eb2e248.png)

2022-01-19 12:49 UTC, kenwongz commented
@Harish110 Please double check your code again
![image](https://user-images.githubusercontent.com/42329568/150133919-a38f1a65-4ed0-4c2b-a4c8-511c070082ee.png)

2022-01-19 13:04 UTC, JSQJ approved these changes
Tested, previous issue fixed

2022-01-19 13:04 UTC, CaeNGnp requested changes
Still a merge blocker for me. Test build is [failing](https://github.com/kenwongz/SimpCity/runs/4867871277?check_suite_focus=true) and formatting issues unresolved.

2022-01-19 13:04 UTC, CaeNGnp commented on SimpCity/Game.cs
> +                }
Dirty diff, please put this portion up back where it was above...

2022-01-19 13:04 UTC, CaeNGnp commented on SimpCity/SimpCity.csproj
> +    <Compile Include="buildings\House.cs" />
Duplicate of line 47.

2022-01-19 13:47 UTC, CaeNGnp approved these changes
That's better

2022-01-19 13:51 UTC, Harish110 commented
> @Harish110 please fix the conflict. Please do it by 21/01/22

Conflict solved. - harish

2022-01-19 13:56 UTC, kenwongz commented
Open this issue again as we have not tested it yet

2022-01-19 14:01 UTC, JSQJ approved these changes
Tested, no issues

2022-01-19 14:04 UTC, kenwongz approved these changes

2022-01-19 14:04 UTC, merged

2022-01-19 14:04 UTC, kenwongz commented
Tested by Kenneth and Jeremy