unit testing for placing mulitple buildings done.
kenwongz/SimpCity pull request #63
Opened 2022-02-02 04:03 UTC by Harish110

2022-02-02 12:24 UTC, kenwongz commented
@Harish110 this also include the scoring for shop right

2022-02-02 12:51 UTC, CaeNGnp requested changes
The added tests scripts for each building types are way too trivial to require their own test method. This unnecessarily adds burden for QA and developers when analysing test results.

Please combine all of the testing of house/factory/highway/shop/etc in one single test method (e.g. `BuildAt_PlacesAllBuildingTypes_WhenCalledProperly`) - we have more than enough cell spaces for these.

2022-02-02 12:51 UTC, CaeNGnp commented on SimpCityTests/GameTests.cs
> +        /// QA-SN-5, US-6:
should remove, see 750a4f5a26587975e4e5b4e9c54e33c01befb67e

2022-02-02 12:55 UTC, Harish110 commented
> @Harish110 this also include the scoring for shop right

Yes @kenwongz

2022-02-03 04:43 UTC, CaeNGnp requested changes

2022-02-03 04:43 UTC, CaeNGnp commented on SimpCityTests/GameTests.cs
> +            game.BuildAt(game.buildingInfo[BuildingTypes.Monument], new CityGridPosition(0, 3));
0,2 **

2022-02-03 05:02 UTC, CaeNGnp approved these changes
Lgtm!

2022-02-03 05:04 UTC, JSQJ approved these changes
the scoring for shop works

2022-02-03 05:19 UTC, merged